#Project ID: lyemosis 
#Project Number: 637239282909
#Address: http://lyemosis.appspot.com/
#Author: Vi Nguyen
#Service Account Name: lyemosis@appspot.gserviceaccount.com
#Client ID: 637239282909-4msf0u4lojej7cibrpi062fl164mt3ad.apps.googleusercontent.com
#Client Secret: tk3cLLyruIkbDbXETouj2cpm

application: lyemosis
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.application

libraries:
- name: webapp2
  version: latest
